/**
 * @file index.js
 * @description SDMS entry point — wires all components together via dependency injection.
 * Demonstrates the full authentication and document workflow.
 *
 * This file also serves as the design-to-code mapping reference:
 * each class below corresponds to a class in the UML Class Diagram.
 */

'use strict';

const Engineer            = require('./auth/engineer');
const Supervisor          = require('./auth/supervisor');
const MFAProvider         = require('./auth/mfa-provider');
const SessionManager      = require('./auth/session-manager');
const AuditLog            = require('./audit/audit-log');
const DocumentRepository  = require('./documents/document-repository');
const DocumentLock        = require('./documents/document-lock');
const { SecurityProxy }   = require('./security/security-proxy');
const { AccessControlService } = require('./security/access-control-service');
const Report              = require('./reports/report');

// ─── Bootstrap: wire dependencies ────────────────────────────────────────────

const auditLog          = new AuditLog();
const mfaProvider       = new MFAProvider();
const sessionManager    = new SessionManager(mfaProvider, auditLog);
const docRepository     = new DocumentRepository();
const securityProxy     = new SecurityProxy(docRepository, auditLog);
const accessControl     = new AccessControlService(auditLog);
const report            = new Report(auditLog);

// ─── Demo: Authentication flow ────────────────────────────────────────

console.log('=== SDMS System Boot ===\n');

const alice = new Engineer('U-001', 'alice@techbuild.com', 'SecurePass123');
const bob   = new Supervisor('U-002', 'bob@techbuild.com', 'SupervisorPass!');

// Step 1: Initiate login (password check + OTP dispatch)
const step1 = sessionManager.initiateLogin(alice, 'SecurePass123');
console.log('[AUTH] Step 1:', step1.message);

// Step 2: Complete login (OTP verification)
const otpCode = mfaProvider.generateCode(alice.userID, alice.email); // simulate receiving OTP
const step2 = sessionManager.completeLogin(alice, otpCode);
console.log('[AUTH] Step 2:', step2.message);

const aliceToken = step2.sessionToken;

// ─── Demo: Document upload via SecurityProxy ──────────────────────────

try {
  accessControl.authorise(alice, aliceToken, 'upload');

  const docID = securityProxy.upload(
    alice.userID,
    {
      name: 'bridge-design-v1.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 1024 * 500,      // 500 KB
      content: 'PDF binary content here'
    },
    {
      title: 'Bridge Design Specification v1',
      category: 'design-specification',
      classificationLevel: 'confidential'
    }
  );
  console.log(`[UPLOAD] Document saved. ID: ${docID}`);

  // ─── Demo: Document reservation ─────────────────────────────────────

  accessControl.authorise(alice, aliceToken, 'reserve');

  const lock = new DocumentLock(docID);

  // Register an observer to simulate conflict notifications
  lock.addObserver(event => {
    console.log(`[NOTIFICATION] Document "${event.docID}" → ${event.type} by ${event.lockedByUserID}`);
  });

  const lockResult = lock.lock(alice.userID);
  console.log(`[RESERVE] ${lockResult.message}`);

} catch (err) {
  console.error('[ERROR]', err.message);
}

// ─── Demo: Supervisor activity report ────────────────────────────────

const step1b = sessionManager.initiateLogin(bob, 'SupervisorPass!');
const otpBob = mfaProvider.generateCode(bob.userID, bob.email);
const step2b = sessionManager.completeLogin(bob, otpBob);
const bobToken = step2b.sessionToken;

try {
  accessControl.authorise(bob, bobToken, 'viewReports');

  const activityReport = report.generate(
    bob.userID,
    new Date(Date.now() - 24 * 60 * 60 * 1000), // last 24h
    new Date()
  );

  console.log(`\n[REPORT] Generated by ${bob.userID}`);
  console.log(`         Period: ${activityReport.period.from} → ${activityReport.period.to}`);
  console.log(`         Total events: ${activityReport.totalEvents}`);
  console.log('         Summary:', activityReport.summary);

} catch (err) {
  console.error('[REPORT ERROR]', err.message);
}
